# Internal helpers. Not exported.

# After migrating a vignette/article .Rmd out of `from_dir`, warn about any
# OTHER files left behind there. Migration moves only the .Rmd, so a sidecar
# file the document depends on (a CSV, an .rds, a linked image) stays put and
# may break things. We can't tell how each file is used, so we list them and
# explain the two cases rather than trying to relocate anything.
#
# `figures/` is excluded: it holds generated output, not a source dependency.
warn_orphaned_siblings <- function(from_dir, moved, dest_dir) {
      if (!dir.exists(from_dir)) return(invisible())

      siblings <- list.files(from_dir, full.names = FALSE, no.. = TRUE)
      siblings <- setdiff(siblings, moved)

      # Exclude things that are definitionally NOT this document's sidecar
      # data, so we don't cry wolf:
      #   - other .Rmd files (they're other vignettes/articles)
      #   - the articles/ and figures/ structural directories
      is_other_rmd <- grepl("\\.Rmd$", siblings, ignore.case = TRUE)
      is_structural <- siblings %in% c("articles", "figures")
      siblings <- siblings[!is_other_rmd & !is_structural]

      if (length(siblings) == 0L) return(invisible())

      message(
            "\nNote: migration moved only the .Rmd. These files remain in ",
            from_dir, ":\n  - ",
            paste(siblings, collapse = "\n  - "),
            "\nIf the document reads a file *at knit time* (e.g. read.csv()), ",
            "move it\nto ", dest_dir, " so it sits beside the source when ",
            "precompiling.\nIf instead the *rendered* output links to a file ",
            "(e.g. an image pkgdown\nmust copy), leave it under vignettes/. ",
            "Files used both ways may need\nto exist in both places."
      )
      invisible()
}

# After knitting `src` -> `out`, warn about statically-linked resources the
# rendered document needs but that aren't present beside the output, where
# pkgdown will look for them. Uses rmarkdown::find_external_resources() -- the
# same detector pkgdown relies on -- run against the SOURCE, which reports
# resources existing relative to the source. Any web-facing resource present
# beside the source but missing beside the output would be copied by pkgdown
# from the wrong place (i.e. not at all).
#
# Scope and honesty:
#   - Only `web == TRUE` resources are checked. A knit-time-only data file
#     (read by code, web == FALSE) is intentionally NOT flagged -- it need not
#     ship.
#   - Generated figures already exist beside the output, so they don't trip.
#   - Detection inherits find_external_resources()'s heuristics (and blind
#     spots); this is a best-effort warning, not a guarantee.
#   - Entirely best-effort: if rmarkdown is unavailable or the scan errors,
#     we say nothing and never interrupt precompile.
warn_missing_output_resources <- function(src, out) {
      if (!requireNamespace("rmarkdown", quietly = TRUE)) return(invisible())

      res <- tryCatch(
            rmarkdown::find_external_resources(src),
            error = function(e) NULL
      )
      if (is.null(res) || nrow(res) == 0L) return(invisible())

      # Web-facing resources only.
      web <- res[isTRUE_vec(res$web), , drop = FALSE]
      if (nrow(web) == 0L) return(invisible())

      out_dir <- dirname(out)
      # A resource is "missing" if its path (relative to the document) doesn't
      # resolve beside the output. find_external_resources only returns paths
      # that exist relative to the source, so this isolates output-side gaps.
      rel_paths <- web$path
      missing <- rel_paths[!file.exists(file.path(out_dir, rel_paths))]
      if (length(missing) == 0L) return(invisible())

      message(
            "\nNote: the rendered ", basename(out), " links to file(s) that ",
            "pkgdown will\nexpect beside it in ", out_dir,
            " but that aren't there:\n  - ",
            paste(missing, collapse = "\n  - "),
            "\nThese look like authored assets (not generated output). Place ",
            "a copy\nunder ", out_dir, " so pkgdown can find and copy them ",
            "when building\nthe site. (Knit-time-only data files are not ",
            "flagged here.)"
      )
      invisible()
}

# Coerce a possibly-logical/character/NA column to a clean logical vector.
isTRUE_vec <- function(x) {
      if (is.logical(x)) return(!is.na(x) & x)
      tolower(as.character(x)) %in% c("true", "t", "1")
}

inject_generated_notice <- function(path, source_path) {
      lines <- readLines(path, warn = FALSE)
      yaml_delims <- which(lines == "---")
      insert_at <- if (length(yaml_delims) >= 2L) yaml_delims[2] else 0L

      notice <- c(
            "",
            "<!--",
            "  =====================================================================",
            "  WARNING: THIS FILE IS GENERATED by rawvignette. Do not edit by hand.",
            paste0("  Source: ", source_path),
            "  Regenerate with: rawvignette::precompile_raw_vignettes()",
            "  =====================================================================",
            "-->"
      )

      new_lines <- append(lines, notice, after = insert_at)
      writeLines(new_lines, path)
}

add_to_rbuildignore <- function(pattern) {
      path <- ".Rbuildignore"
      existing <- if (file.exists(path)) {
            readLines(path, warn = FALSE)
      } else {
            character()
      }
      if (!pattern %in% existing) {
            writeLines(c(existing, pattern), path)
            message("Added `", pattern, "` to .Rbuildignore")
      }
}

package_name <- function() {
      desc <- tryCatch(read.dcf("DESCRIPTION"), error = function(e) NULL)
      if (is.null(desc) || !"Package" %in% colnames(desc)) {
            return("yourpackage")
      }
      unname(desc[1, "Package"])
}

open_for_editing <- function(path) {
      if (!interactive()) return(invisible())
      if (identical(Sys.getenv("TESTTHAT"), "true")) return(invisible())

      if (requireNamespace("rstudioapi", quietly = TRUE) &&
          rstudioapi::isAvailable()) {
            rstudioapi::navigateToFile(path)
      } else {
            tryCatch(
                  utils::file.edit(path),
                  error = function(e) invisible()
            )
      }
      invisible()
}

# Build the skeleton for a raw source file. Articles omit the `vignette:`
# YAML block so R does not register them as package vignettes; pkgdown
# still picks them up from vignettes/articles/.
vignette_skeleton <- function(name, title, pkg, article = FALSE) {
      base_name <- basename(name)

      yaml_head <- c(
            "---",
            paste0('title: "', title, '"'),
            "output: rmarkdown::html_vignette"
      )

      vignette_block <- if (article) {
            character()
      } else {
            c(
                  "vignette: >",
                  paste0("  %\\VignetteIndexEntry{", title, "}"),
                  "  %\\VignetteEngine{knitr::rmarkdown}",
                  "  %\\VignetteEncoding{UTF-8}"
            )
      }

      regen_target <- paste0("vignettes/", name, ".Rmd")
      kind <- if (article) "article" else "vignette"

      c(
            yaml_head,
            vignette_block,
            "---",
            "",
            "```{r setup, include = FALSE}",
            "knitr::opts_chunk$set(",
            "  collapse = TRUE,",
            '  comment  = "#>"',
            ")",
            "```",
            "",
            "```{r}",
            paste0("library(", pkg, ")"),
            "```",
            "",
            paste0("Write ", kind, " content here. This is the source -- edit it freely."),
            "Run `rawvignette::precompile_raw_vignettes()` to regenerate the shipped",
            paste0(kind, " at `", regen_target, "`.")
      )
}
