# Internal helpers. Not exported.

inject_generated_notice <- function(path, source_path) {
      lines <- readLines(path, warn = FALSE)
      yaml_delims <- which(lines == "---")
      insert_at <- if (length(yaml_delims) >= 2L) yaml_delims[2] else 0L

      notice <- c(
            "",
            "<!--",
            "  =====================================================================",
            "  WARNING: THIS FILE IS GENERATED by rawvignette. Do not edit by hand.",
            paste0("  Source: ", source_path),
            "  Regenerate with: rawvignette::precompile_raw_vignettes()",
            "  =====================================================================",
            "-->"
      )

      new_lines <- append(lines, notice, after = insert_at)
      writeLines(new_lines, path)
}

add_to_rbuildignore <- function(pattern) {
      path <- ".Rbuildignore"
      existing <- if (file.exists(path)) {
            readLines(path, warn = FALSE)
      } else {
            character()
      }
      if (!pattern %in% existing) {
            writeLines(c(existing, pattern), path)
            message("Added `", pattern, "` to .Rbuildignore")
      }
}

package_name <- function() {
      desc <- tryCatch(read.dcf("DESCRIPTION"), error = function(e) NULL)
      if (is.null(desc) || !"Package" %in% colnames(desc)) {
            return("yourpackage")
      }
      unname(desc[1, "Package"])
}

open_for_editing <- function(path) {
      if (!interactive()) return(invisible())
      if (identical(Sys.getenv("TESTTHAT"), "true")) return(invisible())

      if (requireNamespace("rstudioapi", quietly = TRUE) &&
          rstudioapi::isAvailable()) {
            rstudioapi::navigateToFile(path)
      } else {
            tryCatch(
                  utils::file.edit(path),
                  error = function(e) invisible()
            )
      }
      invisible()
}

# Build the skeleton for a raw source file. Articles omit the `vignette:`
# YAML block so R does not register them as package vignettes; pkgdown
# still picks them up from vignettes/articles/.
vignette_skeleton <- function(name, title, pkg, article = FALSE) {
      base_name <- basename(name)

      yaml_head <- c(
            "---",
            paste0('title: "', title, '"'),
            "output: rmarkdown::html_vignette"
      )

      vignette_block <- if (article) {
            character()
      } else {
            c(
                  "vignette: >",
                  paste0("  %\\VignetteIndexEntry{", title, "}"),
                  "  %\\VignetteEngine{knitr::rmarkdown}",
                  "  %\\VignetteEncoding{UTF-8}"
            )
      }

      regen_target <- paste0("vignettes/", name, ".Rmd")
      kind <- if (article) "article" else "vignette"

      c(
            yaml_head,
            vignette_block,
            "---",
            "",
            "```{r setup, include = FALSE}",
            "knitr::opts_chunk$set(",
            "  collapse = TRUE,",
            '  comment  = "#>"',
            ")",
            "```",
            "",
            "```{r}",
            paste0("library(", pkg, ")"),
            "```",
            "",
            paste0("Write ", kind, " content here. This is the source — edit it freely."),
            "Run `rawvignette::precompile_raw_vignettes()` to regenerate the shipped",
            paste0(kind, " at `", regen_target, "`.")
      )
}
